name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Install GKE authentication plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True

    - name: Configure Docker to use Google Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/iris-registry/iris-api:${{ github.sha }} .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/iris-registry/iris-api:${{ github.sha }}

    - name: Connect to GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_REGION }}

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/iris-mlgke-api iris-mlgke-api=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/iris-registry/iris-api:${{ github.sha }}
        kubectl rollout status deployment/iris-mlgke-api

